---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: registry-deployment
 labels:
    app: registry
spec:
 replicas: 1
 selector:
   matchLabels: 
    app: registry
 template:
   metadata: 
     labels:
       app: registry
   spec:
     containers:
       - name: registry
         image: registry:2.7.1
         ports:
           - containerPort: 5000
         volumeMounts:
           - name: registry-data
             mountPath: /var/lib/registry
         livenessProbe:
           tcpSocket:
             port: 5000
           initialDelaySeconds: 10 
         readinessProbe:
           tcpSocket:
             port: 5000
           initialDelaySeconds: 10
     volumes:
       - name: registry-data
         persistentVolumeClaim:
            claimName: registry-data-volume 
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  type: LoadBalancer
  selector: 
    app: registry
  ports:
    - port: 5000  
      targetPort: 5000
   

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 100Gi     


# Or if you prefer to use deployment
# kind: Deployment
